### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by kcollignon** [Ticketfly/ember-keyboard#14]
I added in the service and the event listeners as described in the README, but can't seem to get across this error. Any ideas what may be happening?

`Cannot read property 'toString' of undefined` in `keyboard.js:18`

![image](https://cloud.githubusercontent.com/assets/489403/15518942/038838c4-21b4-11e6-8e7a-b4ec2bc4ad35.png)

Here is my component file:

``` javascript
import Ember from 'ember';

export default Ember.Component.extend({
  keyboard: Ember.inject.service(),
  tagName: 'div',
  classNames: ['invoice'],

  activateKeyboard: Ember.on('didInsertElement', function() {
    this.get('keyboard').activate(this);
  }),


  aFunction: Ember.on('keyDown:a', function() {
    console.log('`a` was pressed');
  }),

  anotherFunction: Ember.on('keyDown:ctrl+shift+a', function() {
    console.log('`ctrl+shift+a` was pressed');
  }),
});
```

**Comment by briarsweetbriar** [comment]
Looks like you're using the old readme. You can find updated instructions [here](http://null-null-null.github.io/ember-keyboard/). A lot has changed, but you should be able to get the effect you're looking for in just the first section of the new guides.

**Comment by kcollignon** [comment]
Thanks @null-null-null that worked. Another quick question, is there any way to get an event listener for multiple number keystrokes? i.e.- `ctrl+12` ?

**Comment by briarsweetbriar** [comment]
There's support for `Ember.on(keyDown('ctrl+1'), keyDown('ctrl+2'), function() { ... })`, which will fire if either 1 or 2 is pressed, but I think that's different from what you're asking. Do you want the event to fire if both are pressed simultaneously? Or if 1 is pressed, followed by 2? Neither are supported out of the box by `ember-keyboard`, but you could build something out locally. Might be an interesting feature to add, too. I'd have to think about it more though.
